version: '3'
services:

  microservice:
    image: microservice
    build: 
      context: ./microservice
      dockerfile: Dockerfile-dev
    container_name: microservice
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./microservice/src:/app/src:z
    ports:
     - "4000:80"
    environment:
     - PORT=80
     - NODE_ENV=development
    restart: always

